@url = http://localhost:5000/agendas-module
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MGRmZTI5Yi0wYzJhLTQ0N2ItYjIzMi0yYTM4ZmMwY2IwMGUiLCJ1bmlxdWVfbmFtZSI6IjUwZGZlMjliLTBjMmEtNDQ3Yi1iMjMyLTJhMzhmYzBjYjAwZSIsImp0aSI6IjE0Mjc4NWVjLTAzOTktNGFlMi1hMDRlLWRlMDdjYTk5ZTdiNCIsImlhdCI6IjE3MDkxNTE5MzMxNzEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidGlja2V0cyIsInVzZXJzIl0sIm5iZiI6MTcwOTE1MTkzMywiZXhwIjoxNzA5MTg3OTMzLCJpc3MiOiJjb25mYWIifQ.l3ZFnrDLFAiwgtrW_wz27Cz1XqmJeVKV5QcFwcCG7oE

###
GET {{url}}

### Assign regular agenda slot
PUT {{url}}/agendas/ec46ee3c-212a-44ad-a96b-ab7425728fb2/slots/regular
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "agendaTrackId": "34953198-3859-4585-9709-9db5511a9833",
  "agendaSlotId": "d27c3975-e099-4990-8e0b-f85e846e1489",
  "agendaItemId": "bddebff7-7aab-4d6b-bb1e-be6a591bdbe3"
}